<?php

use Bitrix\Main\Loader;
use Rexp\Form\Infrastructure\Bitrix\ServiceLocator\Bootstrap;

Loader::registerAutoLoadClasses('rexp.form', [
    'Rexp\\Form\\Domain\\Entity\\Form' => 'lib/Domain/Entity/Form.php',
    'Rexp\\Form\\Domain\\ValueObject\\FormCode' => 'lib/Domain/ValueObject/FormCode.php',
    'Rexp\\Form\\Application\\DTO\\SaveFormCommand' => 'lib/Application/DTO/SaveFormCommand.php',
    'Rexp\\Form\\Application\\Factory\\FormFactory' => 'lib/Application/Factory/FormFactory.php',
    'Rexp\\Form\\Application\\Service\\FormManagerService' => 'lib/Application/Service/FormManagerService.php',
    'Rexp\\Form\\Application\\Service\\FormReadService' => 'lib/Application/Service/FormReadService.php',
    'Rexp\\Form\\Application\\Service\\FormPublishService' => 'lib/Application/Service/FormPublishService.php',
    'Rexp\\Form\\Application\\Service\\FormDiagnosticsService' => 'lib/Application/Service/FormDiagnosticsService.php',
    'Rexp\\Form\\Application\\Service\\FormDraftService' => 'lib/Application/Service/FormDraftService.php',
    'Rexp\\Form\\Access\\ActionDictionary' => 'lib/Access/ActionDictionary.php',
    'Rexp\\Form\\Access\\Permission\\PermissionDictionary' => 'lib/Access/Permission/PermissionDictionary.php',
    'Rexp\\Form\\Access\\Permission\\FormPermissionTable' => 'lib/Access/Permission/FormPermissionTable.php',
    'Rexp\\Form\\Access\\Role\\RoleDictionary' => 'lib/Access/Role/RoleDictionary.php',
    'Rexp\\Form\\Access\\Role\\FormRoleTable' => 'lib/Access/Role/FormRoleTable.php',
    'Rexp\\Form\\Access\\Role\\FormRoleRelationTable' => 'lib/Access/Role/FormRoleRelationTable.php',
    'Rexp\\Form\\Application\\Service\\FormPermissionService' => 'lib/Application/Service/FormPermissionService.php',
    'Rexp\\Form\\Application\\Service\\FormRuntimeService' => 'lib/Application/Service/FormRuntimeService.php',
    'Rexp\\Form\\Application\\Service\\RuntimeSubmissionService' => 'lib/Application/Service/RuntimeSubmissionService.php',
    'Rexp\\Form\\Application\\Service\\RuntimeBizprocService' => 'lib/Application/Service/RuntimeBizprocService.php',
    'Rexp\\Form\\Application\\Service\\FormSettingsService' => 'lib/Application/Service/FormSettingsService.php',
    'Rexp\\Form\\Application\\Service\\FormTemplateService' => 'lib/Application/Service/FormTemplateService.php',
    'Rexp\\Form\\Application\\Service\\FormTemplateCatalogService' => 'lib/Application/Service/FormTemplateCatalogService.php',
    'Rexp\\Form\\Application\\Service\\FormTemplateCreateService' => 'lib/Application/Service/FormTemplateCreateService.php',
    'Rexp\\Form\\Application\\Service\\FormTargetResolverService' => 'lib/Application/Service/FormTargetResolverService.php',
    'Rexp\\Form\\Application\\Service\\FormImportExportService' => 'lib/Application/Service/FormImportExportService.php',
    'Rexp\\Form\\Application\\Service\\FormExportService' => 'lib/Application/Service/FormExportService.php',
    'Rexp\\Form\\Application\\Service\\FormImportService' => 'lib/Application/Service/FormImportService.php',
    'Rexp\\Form\\Application\\Service\\FormVersionService' => 'lib/Application/Service/FormVersionService.php',
    'Rexp\\Form\\Application\\Service\\MockSubmitDiagnosticsService' => 'lib/Application/Service/MockSubmitDiagnosticsService.php',
    'Rexp\\Form\\Application\\Service\\TemplatePreviewService' => 'lib/Application/Service/TemplatePreviewService.php',
    'Rexp\\Form\\Application\\Service\\FormStateAssetService' => 'lib/Application/Service/FormStateAssetService.php',
    'Rexp\\Form\\Application\\Service\\RuntimeDynamicOptionsService' => 'lib/Application/Service/RuntimeDynamicOptionsService.php',
    'Rexp\\Form\\Application\\Service\\RuntimeValueNormalizerService' => 'lib/Application/Service/RuntimeValueNormalizerService.php',
    'Rexp\\Form\\Application\\Service\\RuntimeConditionEvaluatorService' => 'lib/Application/Service/RuntimeConditionEvaluatorService.php',
    'Rexp\\Form\\Application\\Service\\RuntimeRuleEvaluatorService' => 'lib/Application/Service/RuntimeRuleEvaluatorService.php',
    'Rexp\\Form\\Application\\Service\\RuntimeFieldValidationService' => 'lib/Application/Service/RuntimeFieldValidationService.php',
    'Rexp\\Form\\Application\\Service\\RuntimeFileService' => 'lib/Application/Service/RuntimeFileService.php',
    'Rexp\\Form\\Application\\Service\\RuntimePublicFormBuilderService' => 'lib/Application/Service/RuntimePublicFormBuilderService.php',
    'Rexp\\Form\\Application\\Service\\RuntimeDirectoryService' => 'lib/Application/Service/RuntimeDirectoryService.php',
    'Rexp\\Form\\Application\\UseCase\\Designer\\DesignerFormUseCase' => 'lib/Application/UseCase/Designer/DesignerFormUseCase.php',
    'Rexp\\Form\\Application\\UseCase\\Designer\\DesignerMetadataUseCase' => 'lib/Application/UseCase/Designer/DesignerMetadataUseCase.php',
    'Rexp\\Form\\Application\\UseCase\\Designer\\DesignerHistoryUseCase' => 'lib/Application/UseCase/Designer/DesignerHistoryUseCase.php',
    'Rexp\\Form\\Application\\UseCase\\Designer\\DesignerSubmitUseCase' => 'lib/Application/UseCase/Designer/DesignerSubmitUseCase.php',
    'Rexp\\Form\\Infrastructure\\Persistence\\FormRepository' => 'lib/Infrastructure/Persistence/FormRepository.php',
    'Rexp\\Form\\Infrastructure\\Persistence\\FormVersionRepository' => 'lib/Infrastructure/Persistence/FormVersionRepository.php',
    'Rexp\\Form\\Infrastructure\\Persistence\\FormDraftRepository' => 'lib/Infrastructure/Persistence/FormDraftRepository.php',
    'Rexp\\Form\\Infrastructure\\Persistence\\TableNames' => 'lib/Infrastructure/Persistence/TableNames.php',
    'Rexp\\Form\\Infrastructure\\Persistence\\Orm\\FormTable' => 'lib/Infrastructure/Persistence/Orm/FormTable.php',
    'Rexp\\Form\\Infrastructure\\Persistence\\Orm\\FormVersionTable' => 'lib/Infrastructure/Persistence/Orm/FormVersionTable.php',
    'Rexp\\Form\\Infrastructure\\Persistence\\Orm\\FormDraftTable' => 'lib/Infrastructure/Persistence/Orm/FormDraftTable.php',
    'Rexp\\Form\\Infrastructure\\Persistence\\Orm\\FormSubmissionTable' => 'lib/Infrastructure/Persistence/Orm/FormSubmissionTable.php',
    'Rexp\\Form\\Infrastructure\\Event\\FormEventDispatcher' => 'lib/Infrastructure/Event/FormEventDispatcher.php',
    'Rexp\\Form\\Infrastructure\\Bitrix\\ServiceLocator\\Bootstrap' => 'lib/Infrastructure/Bitrix/ServiceLocator/Bootstrap.php',
    'Rexp\\Form\\Controller\\Designer' => 'lib/Controller/Designer.php',
    'Rexp\\Form\\Controller\\Runtime' => 'lib/Controller/Runtime.php',
    'Rexp\\Form\\Bizproc\\FormSubmissionDocument' => 'lib/Bizproc/FormSubmissionDocument.php',
]);

if (!defined('REXP_FORM_SKIP_BOOTSTRAP') || REXP_FORM_SKIP_BOOTSTRAP !== true) {
    Bootstrap::register();
}
